deploy:
  provider: pypi
  password:
    secure: eUsXVNsHfyU9jbKasEE6m1v4p8iTc8LmBMXR0kAIcEbwx8IYA7cQIaa4exahTqFAQnMYDhjgfldPnkwawiag2878SyiLJAOK63I7QYfYU+COauXCinKeQPjIFfoDYif5gPh9qLzcDxAkx6oSizkLBDLujlSbE8xDSfOWC5Ank/D4eGfla+KcumtYovPibGtwMN+W3TxAAiREfAuGldOb6i5XwuMqNO3l5aIJVLgG5Ba4xECO/KUw8QBIvr03+x01TJVrJn1nBLnaj7Oyq56BXwBD+QcZMWeP4wUcMaRo4HkrVD8IrVx2V4kithRE5Iqbh6QvC/akbMMSR6A0fTujo4iFWExym3dlUnwEXHR4APXoVwF5NmpOQPH2sWGd5VK41dbQ5WLQpJ78QPVlHL7Xertp6zuuHzAUeaE99dXg8X0JYk1wygdTLsJDfOqVeprtMCKySDizUpSrFi61/Zij7NzNguIh31jbwDPgLtf1fx83mGo9bdhTnVksSi2UEpHgAmlQmltS8I7w69Y95u++ZWz+urRNVWrj9jybFzqTM2RJCfGQN+9M7fhKgn7rgAlJbHvVelI26mq05pi541JPUpKjYZU2+3WplMcmixfRHtvZ8duGpxlVi6xRGxAMF6j8IL6cNQ2z1LQwIZasNVmhguVP7xkq3BPD+YdeGsjPA1g=
  user: pythad
  distributions: sdist bdist_wheel
  on:
    python: 3.6
    repo: pythad/nider
    tags: true
before_install:
    - python --version
    - pip install -U pip
install: pip install -U tox-travis
language: python
python:
    - 3.6
    - 3.5
    - 3.4
script: tox
